version: '3'
server:
    command: "php ./worker.php"

http:
    address: 0.0.0.0:80
    pool:
        num_workers: 5
        debug: false
    middleware: [ "static", "headers" ]
    static:
        dir: "./public"
        forbid: [ ".php", ".htaccess" ]
    headers:
        response:
            "Cache-Control": "no-cache"

logs:
    mode: production
    level: warn
